///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b8f58dbd-9699-404c-93b5-b0dac9706489")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("b8f58dbd-9699-404c-93b5-b0dac9706489")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "b8f58dbd-9699-404c-93b5-b0dac9706489", ".\\RepositoryImages\\MyTestRepositoryb8f58dbd.rximgres")
        {
            _calculator = new MyTestRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b8f58dbd-9699-404c-93b5-b0dac9706489")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("5f888659-7baa-47fe-8faf-b104d6742bd1")]
        public virtual MyTestRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("5f888659-7baa-47fe-8faf-b104d6742bd1")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num4buttonInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _text8Info;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _landmarktargetInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "5f888659-7baa-47fe-8faf-b104d6742bd1", "")
            {
                _num4buttonInfo = new RepoItemInfo(this, "Num4Button", ".//container[@automationid='NumberPad']/button[@automationid='num4Button']", ".//button[@automationid='num4Button']", 30000, null, "a22fc265-a930-45d2-9a12-bf29b8df85bd");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//container[@automationid='StandardOperators']/button[@automationid='minusButton']/text[@name='']", ".//text[@name='']", 30000, null, "1fa9e2a8-b629-454d-b4f5-06c2eefa6146");
                _text8Info = new RepoItemInfo(this, "Text8", ".//container[@automationid='NumberPad']/button[@automationid='num8Button']/text[@name='8']", ".//text[@name='8']", 30000, null, "826e97f1-e41f-4352-a098-b83c1ac77ef5");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']", ".//button[@automationid='equalButton']", 30000, null, "db7ccb4c-ddb6-40a4-a67e-20c22d78b8d8");
                _landmarktargetInfo = new RepoItemInfo(this, "LandmarkTarget", "?/?/container[@classname='LandmarkTarget']", "?/?/container[@classname='LandmarkTarget']", 30000, null, "1dca0071-9536-4ffa-ab98-92fe9a0d0273");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f888659-7baa-47fe-8faf-b104d6742bd1")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f888659-7baa-47fe-8faf-b104d6742bd1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num4Button item.
            /// </summary>
            [RepositoryItem("a22fc265-a930-45d2-9a12-bf29b8df85bd")]
            public virtual Ranorex.Button Num4Button
            {
                get
                {
                    return _num4buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num4Button item info.
            /// </summary>
            [RepositoryItemInfo("a22fc265-a930-45d2-9a12-bf29b8df85bd")]
            public virtual RepoItemInfo Num4ButtonInfo
            {
                get
                {
                    return _num4buttonInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("1fa9e2a8-b629-454d-b4f5-06c2eefa6146")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("1fa9e2a8-b629-454d-b4f5-06c2eefa6146")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Text8 item.
            /// </summary>
            [RepositoryItem("826e97f1-e41f-4352-a098-b83c1ac77ef5")]
            public virtual Ranorex.Text Text8
            {
                get
                {
                    return _text8Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text8 item info.
            /// </summary>
            [RepositoryItemInfo("826e97f1-e41f-4352-a098-b83c1ac77ef5")]
            public virtual RepoItemInfo Text8Info
            {
                get
                {
                    return _text8Info;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("db7ccb4c-ddb6-40a4-a67e-20c22d78b8d8")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("db7ccb4c-ddb6-40a4-a67e-20c22d78b8d8")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The LandmarkTarget item.
            /// </summary>
            [RepositoryItem("1dca0071-9536-4ffa-ab98-92fe9a0d0273")]
            public virtual Ranorex.Container LandmarkTarget
            {
                get
                {
                    return _landmarktargetInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The LandmarkTarget item info.
            /// </summary>
            [RepositoryItemInfo("1dca0071-9536-4ffa-ab98-92fe9a0d0273")]
            public virtual RepoItemInfo LandmarkTargetInfo
            {
                get
                {
                    return _landmarktargetInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
